### ISSUE TITLE
How to use with Queue. Can mailer be made public?

### ISSUE THREAD

**Issue by VineFiner** [sersoft-gmbh/SwiftSMTP#3]
```
        @inlinable
        public
        func mailer(for eventLoop: EventLoop) -> Mailer {
            storage.mailers[ObjectIdentifier(eventLoop)]!
        }
```
EmailJob

```
context.application.swiftSMTP.mailer(for: context.eventLoop).send(email: realEmail)
```

**Comment by ffried** [comment]
@VineFiner Can you give a little more context? What Queue are you referring to?
The problem is, that this method is not safe. If you pass in an `EventLoop` that does not belong to the Application's `EventLoopGroup`, it'll crash.

If there are other objects (like `Request`) that are `EventLoop`-bound and need access to a `Mailer`, please list those and I'll see if I can add support for them.

**Comment by VineFiner** [comment]
> @VineFiner您能否再提供一些背景信息？您指的是什么队列？
> 问题是这种方法不安全。如果您传递的`EventLoop`不属于Application的`EventLoopGroup`，则会崩溃。
> 
> 如果还有其他受限制的对象（例如`Request`），`EventLoop`并且需要访问`Mailer`，请列出这些对象，然后看看是否可以添加对它们的支持。

This is demo 

https://github.com/madsodgaard/vapor-auth-template

https://github.com/madsodgaard/vapor-auth-template/blob/master/Sources/App/Jobs/EmailJob.swift

```
import Vapor
import Queues
import Mailgun

struct EmailPayload: Codable {
    let email: AnyEmail
    let recipient: String
    
    init<E: Email>(_ email: E, to recipient: String) {
        self.email = AnyEmail(email)
        self.recipient = recipient
    }
}

struct EmailJob: Job {
    typealias Payload = EmailPayload
    
    func dequeue(_ context: QueueContext, _ payload: EmailPayload) -> EventLoopFuture<Void> {
        let mailgunMessage = MailgunTemplateMessage(
            from: context.appConfig.noReplyEmail,
            to: payload.recipient,
            subject: payload.email.subject,
            template: payload.email.templateName,
            templateData: payload.email.templateData
        )
        
        return context.mailgun().send(mailgunMessage).transform(to: ())
    }
}
```
I want to replace Mailgun, there is no Request here.

**Comment by VineFiner** [comment]
> @VineFiner Can you give a little more context? What Queue are you referring to?
> 
> The problem is, that this method is not safe. If you pass in an `EventLoop` that does not belong to the Application's `EventLoopGroup`, it'll crash.
> 
> 
> 
> If there are other objects (like `Request`) that are `EventLoop`-bound and need access to a `Mailer`, please list those and I'll see if I can add support for them.


For vapor expansion, evenloop may not be exposed.  If necessary, users can write differentiated extensions to achieve high performance.

**Comment by ffried** [comment]
I've just released a new release candidate which fixes your problems and simplifies the Vapor support layer.
You now have access to the shared Mailer using `application.swiftSMTP.mailer` - or in your case `context.application.swiftSMTP.mailer`.
For requests, you can still use `request.swiftSMTP.mailer`.

For details, see the [release notes of RC2](https://github.com/sersoft-gmbh/SwiftSMTP/releases/tag/2.0.0-rc.2.0)
